name: Test Upload Artifact

on: [push]

jobs:
  test-upload:
    runs-on: windows-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create dummy file
        run: echo "test file content" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: test.txt


